services:
  meshtastic-proxy:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
